# nixpacks.toml - Fixed configuration for Railway

providers = ["python"]

[variables]
PYTHONUNBUFFERED = "1"
PYTHONDONTWRITEBYTECODE = "1"

[phases.setup]
nixPkgs = [
    "python311",
    "python311Packages.pip", 
    "python311Packages.setuptools",
    "python311Packages.wheel",
    "pkg-config",
    "libffi",
    "openssl",
    "portaudio",
    "ffmpeg",
    "alsa-lib"
]

[phases.install]
cmds = [
    "pip install --upgrade pip setuptools wheel",
    "pip install --no-cache-dir -r requirements.txt"
]

[start]
cmd = "python main.py"
