[providers]
python = "3.11"

[variables]
PYTHONUNBUFFERED = "1"
PYTHONDONTWRITEBYTECODE = "1"

[phases.setup]
nixPkgs = [
    "python311",
    "python311Packages.pip",
    "python311Packages.setuptools",
    "python311Packages.wheel",
    "pkg-config",
    "libffi",
    "openssl",
    "portaudio",
    "ffmpeg",
    "alsa-lib",
    "pulseaudio"
]

[phases.install]
cmds = [
    "pip install --upgrade pip setuptools wheel",
    "pip install --no-cache-dir -r requirements.txt"
]

[phases.build]
cmds = [
    "python -c 'import torch; print(f\"PyTorch version: {torch.__version__}\")'",
    "python -c 'import pipecat; print(f\"Pipecat installed successfully\")'",
    "python -c 'import deepgram; print(f\"Deepgram SDK ready\")'"
]

[start]
cmd = "python main.py"
