name: n8n-voice-bot
region: nyc
services:
- name: api
  github:
    repo: Mehdi-Touij/voice-call-service
    branch: main
  http_port: 8000
  instance_size_slug: basic-xxs
  instance_count: 1
  health_check:
    http_path: /health
    timeout_seconds: 3
    period_seconds: 10
  run_command: uvicorn main:app --host 0.0.0.0 --port 8000
  envs:
  - key: N8N_WEBHOOK_URL
    value: "https://primary-production-97cb.up.railway.app/webhook/voice-session"
  - key: DEEPGRAM_API_KEY
    type: SECRET
  - key: ELEVENLABS_API_KEY
    type: SECRET
  - key: ELEVENLABS_VOICE_ID
    type: SECRET
  - key: DAILY_API_KEY
    type: SECRET
  - key: LOG_LEVEL
    value: "INFO"
